### PR TITLE
Load earthquakes data in tiles, use USGS API

### PR DESCRIPTION
**Pull request by pjanik**
I work alone now on this project, so not sure if I should just merge it or wait for review (@scytacki, @dstrawberrygirl)? I'm happy that the final lines of code balance is actually negative (-93). :wink: I'll remove our JSON datasets and regions from repo later, so this PR doesn't get ridiculously huge.

The most important changes:
- `actions/index.js`, `setEarthquakeDataTiles` function
- `earthquake-data-api.js`
- simplified reducers (`reducers/index.js`)
- `map-tile-helpers.js` can be useful to understand tiles math

### CODE REVIEW

**Comment by scytacki** [comment]
@dstrawberrygirl it would be great if you could look at this. Even though you aren't on the project right now, it is helpful to have some review.

**Comment by dstrawberrygirl** [comment]
When I previously worked on apps like this, tiles were requested for server-side imagery, and the points of interest would come down in one batch for the currently-displayed visible bounds. In this situation, we're breaking up the batch into tiles - this will help a lot with the USGS direct requests, since there is such a low limit on the quantity of data per request, though it may not be as necessary if we were to use our own data source... the tile-based approach means we can more easily go directly to the USGS, so it's probably the right call.

@pjanik I've not had a chance to really dig into this PR to be sure - with this system, do we cut off on a tile-by-tile basis if there is too much data for one specific region, or does that filter bubble up to the rest of the view? If it were map-wide, you could have a lower magnitude cutoff that varied by number of total results, giving a more consistent view. For example, why could I see a mag 3 in one area, but none in another? I think as long as the cutoff point is consistent then I'd be more accepting of the visible results - or perhaps where we have a truncated tile, could we display an icon / mark with details on hover/click "more data available in this area - zoom to show" or something like that.

**Comment by pjanik** [comment]
> this will help a lot with the USGS direct requests, since there is such a low limit on the quantity of data per request, though it may not be as necessary if we were to use our own data source...

I'd say tile-based approach is better in our case. We download a lot of data, probably it's a bit different from POIs.

If we naively asked API about all the earthquakes for the current bounds, then even a very small map panning action would trigger download of 100k (or more) earthquakes - a lot of data, pretty slow and 99% of it has been already downloaded in the previous requests. Definitely we don't want this.

So, we could implement client-side caching and calculate the area diff that we need to download. It would work in a similar way to the current tiles-based approach, but then it's not possible to have server-side caching. Each request would depend on user actions, so it would be pretty random. And the client implementation would be probably more complicated than now.

Also, tile-based approach let us switch to static, pregenerated tiles in the future. @scytacki has been considering that as a long-term plan if we don't want to maintain our own DB and API.

> with this system, do we cut off on a tile-by-tile basis if there is too much data for one specific region, or does that filter bubble up to the rest of the view?

We cut off on a tile-by-tile basis. If tile has more than 12k earthquakes, we discard the weakest ones.

> For example, why could I see a mag 3 in one area, but none in another?

The current implementation is pretty simple - we just download data for given tile, set 12k limit and some zoom-based mag limit. So it's possible that one tile has less than 12k earthquakes and they all fit mag 3-10 range. However another tile might have so many earthquakes that 12k limit is affecting it and we have to discard the weakest ones (e.g. those with magnitude 3-4). That's why magnitude range can vary between visible tiles.

> I think as long as the cutoff point is consistent then I'd be more accepting of the visible results 

Right, agree, we've been thinking about that. We've discussed that a few times on Slack, there are quite a few ideas, but none of them is perfect and it's a bit complicated, so personally I'd focus on it later (e.g. when we have our own API, maybe combination of tile size adjustments and per-tile data limit can practically solve this issue).

**Comment by pjanik** [comment]
I'm not sure what's the conclusion here. I think tiles are better in our case and re inconsistent magnitude, I would keep it in mind and try to address later.
Is it okay to merge then?

**Pull request merged**
